services:
  # login with admin/admin
  # add the "http://prometheus:9090" as a data source
  # and import the grafana_dashboard.json file to see the metrics
  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - '3000:3000'
    restart: always
    environment:
      # Configure Grafana for reverse proxy with /grafana path
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_DOMAIN=localhost
      - GF_SERVER_HTTP_PORT=3000
      # Security settings
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      # Optional: Enable anonymous access if needed
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - grafana:/var/lib/grafana
      # Optional: Mount custom grafana.ini if you prefer file-based config
      # - ./grafana.ini:/etc/grafana/grafana.ini
    networks:
      - external

volumes:
  grafana:

networks:
  external:
    name: trading_network
