services:
  clickhouse-server:
    image: clickhouse/clickhouse-server:25.6-alpine
    container_name: clickhouse-server
    restart: unless-stopped
    ports:
      - '8124:9000' # TCP native protocol
      - '8123:8123' # HTTP
      # - '9009:9009' # Interserver
      - '9363:9363' # Prometheus
    environment:
      # default settings
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - .volumes/clickhouse_data:/var/lib/clickhouse
      - .volumes/clickhouse_logs:/var/log/clickhouse-server
      - ./docker/clickhouse/local/config.xml:/etc/clickhouse-server/config.xml:ro
      - ./docker/clickhouse/local/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./docker/clickhouse/init:/docker-entrypoint-initdb.d
    ulimits:
      nproc: 65535
      nofile: 262144
    networks:
      - external
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '10'
        compress: 'true'

networks:
  external:
    name: trading_network
